#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: 'TRUE'
#    hibernate:
#      ddl-auto: update
#    open-in-view: 'false'
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: 'true'
#    throw-exception-if-no-handler-found: true
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    password: 'toor'
#    username: 'root'
#    url: jdbc:mysql://localhost:3306/snews?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#  web:
#    resources:
#      add-mappings: false
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor: TRACE
#        SQL: DEBUG
#      nodeValue: WARN
#    blog: WARN
#server:
#  port: 8080
#  error:
#    whitelabel:
#      enabled: true

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 'toor'
    username: 'root'
    url: jdbc:mysql://localhost:3306/snews?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080