spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_CONNECTION_STRING}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:/static
  servlet:
    multipart:
      max-file-size: 1MB
logging:
  level:
        org.springframework.security: trace
server:
  servlet:
    session:
      cookie:
        secure: true
env:
  gmail-username: ${GMAIL_USERNAME}
  gmail-password: ${GMAIL_PASSWORD}
