spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/snews?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: toor
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:/static
  mail:
    username: noreply@snews.com
logging:
  level:
        org.springframework.security: trace
#    org.springframework.security: error

server:
  servlet:
    session:
      cookie:
        secure: true
